//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatelteaEntities : DbContext
    {
        public PatelteaEntities()
            : base("name=PatelteaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<banner_master> banner_master { get; set; }
        public virtual DbSet<Company_master> Company_master { get; set; }
        public virtual DbSet<contact_master> contact_master { get; set; }
        public virtual DbSet<distibuter_master> distibuter_master { get; set; }
        public virtual DbSet<feedback_master> feedback_master { get; set; }
        public virtual DbSet<product_master> product_master { get; set; }
    }
}
