//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatelTeaSource.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_master
    {
        public long p_id { get; set; }
        public string pname { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public Nullable<System.DateTime> udate { get; set; }
        public string photo { get; set; }
        public Nullable<int> status { get; set; }
    }
}
